set_property IOSTANDARD LVCMOS33 [get_ports pwm0_0]
set_property IOSTANDARD LVCMOS33 [get_ports pwm0_1]
set_property IOSTANDARD LVCMOS33 [get_ports pwm0_2]
set_property IOSTANDARD LVCMOS33 [get_ports pwm0_3]
set_property PACKAGE_PIN W14 [get_ports pwm0_0]
set_property PACKAGE_PIN Y14 [get_ports pwm0_1]
set_property PACKAGE_PIN T11 [get_ports pwm0_2]
set_property PACKAGE_PIN T10 [get_ports pwm0_3]

set_property IOSTANDARD LVCMOS33 [get_ports speed_sensor_D0_0]
set_property IOSTANDARD LVCMOS33 [get_ports speed_sensor_D0_2]
set_property IOSTANDARD LVCMOS33 [get_ports speed_sensor_D0_1]
set_property IOSTANDARD LVCMOS33 [get_ports speed_sensor_D0_3]
set_property PACKAGE_PIN Y18 [get_ports speed_sensor_D0_0]
set_property PACKAGE_PIN Y19 [get_ports speed_sensor_D0_1]
set_property PACKAGE_PIN Y16 [get_ports speed_sensor_D0_2]
set_property PACKAGE_PIN Y17 [get_ports speed_sensor_D0_3]
set_property IOSTANDARD LVCMOS33 [get_ports speed_sensor_reset]
set_property PACKAGE_PIN U18 [get_ports speed_sensor_reset]

set_property IOSTANDARD LVCMOS33 [get_ports IIC_0_0_scl_io]
set_property IOSTANDARD LVCMOS33 [get_ports IIC_0_0_sda_io]
set_property IOSTANDARD LVCMOS33 [get_ports IIC_1_0_scl_io]
set_property IOSTANDARD LVCMOS33 [get_ports IIC_1_0_sda_io]
set_property PACKAGE_PIN P16 [get_ports IIC_0_0_scl_io]
set_property PACKAGE_PIN P15 [get_ports IIC_0_0_sda_io]
set_property PACKAGE_PIN U12 [get_ports IIC_1_0_scl_io]
set_property PACKAGE_PIN T14 [get_ports IIC_1_0_sda_io]

set_property IOSTANDARD LVCMOS33 [get_ports sonar_echo_0]
set_property IOSTANDARD LVCMOS33 [get_ports sonar_echo_1]
set_property IOSTANDARD LVCMOS33 [get_ports sonar_trig_0]
set_property IOSTANDARD LVCMOS33 [get_ports sonar_trig_1]
set_property PACKAGE_PIN V16 [get_ports sonar_echo_0]
set_property PACKAGE_PIN W16 [get_ports sonar_echo_1]
set_property PACKAGE_PIN V12 [get_ports sonar_trig_0]
set_property PACKAGE_PIN W13 [get_ports sonar_trig_1]
