
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2024.1
* DO NOT EDIT.
*
* Copyright (C) 2010-2025 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xgpio.h"

/*
* The configuration table for devices
*/

XGpio_Config XGpio_ConfigTable[XPAR_XGPIO_NUM_INSTANCES] =
{
	{
		XPAR_GPIO_BTNS_SWS_DEVICE_ID,
		XPAR_GPIO_BTNS_SWS_BASEADDR,
		XPAR_GPIO_BTNS_SWS_INTERRUPT_PRESENT,
		XPAR_GPIO_BTNS_SWS_IS_DUAL
	},
	{
		XPAR_GPIO_LEDS_RGB_DEVICE_ID,
		XPAR_GPIO_LEDS_RGB_BASEADDR,
		XPAR_GPIO_LEDS_RGB_INTERRUPT_PRESENT,
		XPAR_GPIO_LEDS_RGB_IS_DUAL
	},
	{
		XPAR_GPIO_INTR_MPU_DEVICE_ID,
		XPAR_GPIO_INTR_MPU_BASEADDR,
		XPAR_GPIO_INTR_MPU_INTERRUPT_PRESENT,
		XPAR_GPIO_INTR_MPU_IS_DUAL
	}
};


